# This file was generated by GoReleaser. DO NOT EDIT.
cask "poi" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "742f5b3e2d206dd3e1807408b1fed5b783245c78fe4697fcf001ddde0c2c0759"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
    on_arm do
      sha256 "af069f8c2d3db98477b7f0a3b64095dab28e1ed08fb48d8d92c12d5a0d318b7c"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
  end

  on_linux do
    on_intel do
      sha256 "facd53b9bd00db44ccca7874747d0e113a6ad7dee12badc9ccfbe63885eb7b0f"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_linux_amd64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
    on_arm do
      sha256 "c9ead8c2554907848e0f300733dd5be25fdf016f8e42aa0109a610099f867099"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_linux_arm64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
  end

  name "poi"
  desc "Keeps an id-anchored record beside your code — intent, invariants and gotchas, mechanically rechecked"
  homepage "https://pointegrity.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poi"]
    end
  end

  # No zap stanza required

end
