# This file was generated by GoReleaser. DO NOT EDIT.
cask "poi" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "e30f8f6fe6ce389efc24ef163dba5cee690af112f5e71d7ccec9dd00b16e8a76"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
    on_arm do
      sha256 "a6b3d051189554329af7911a5f0539712b5c2abcd9b40aa4d7535df80888e8d2"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3284b8169e9db11cba8c701b9711f79d1c747824e6590a730afc0d207015082"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_linux_amd64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
    on_arm do
      sha256 "aabc75c31427cbf0cb42b9b25273819ef1a2e5941edbeaa23c1bd83fade31b53"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_linux_arm64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
  end

  name "poi"
  desc "Keeps an id-anchored record beside your code — intent, invariants and gotchas, mechanically rechecked"
  homepage "https://pointegrity.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poi"]
    end
  end

  # No zap stanza required

end
