# This file was generated by GoReleaser. DO NOT EDIT.
cask "poi" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "8c0a67ef352b48c21006366b5f75d85af23859ac2f9996612a420a2c28916bc8"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
    on_arm do
      sha256 "8d9471fec8995798162137298c6df8b6e332aff00f9510bf319909fbb8c197a3"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
  end

  on_linux do
    on_intel do
      sha256 "daebd54991c4bdb8ee52e23cff98a5101c970ca0b4b6e06da70bfcf28e9a37ae"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_linux_amd64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
    on_arm do
      sha256 "0201617f87eaa286c56cac29fa1f4bc5b8e09dc298b9df18f1034a5fb92597c0"
      url "https://github.com/pointegrity/poi/releases/download/v#{version}/poi_#{version}_linux_arm64.tar.gz",
        verified: "github.com/pointegrity/poi/"
    end
  end

  name "poi"
  desc "Keeps an id-anchored record beside your code — intent, invariants and gotchas, mechanically rechecked"
  homepage "https://pointegrity.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poi"]
    end
  end

  # No zap stanza required

end
